name: flutter_birds
description: "A flutter project to tweet"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  collection: ^1.18.0

  # l10n
  flutter_localizations:
    sdk: flutter
  intl: any

  # freezed
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

  # riverpod
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # flutter_hooks
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1

  # firebase
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.3

  # go_router
  go_router: ^14.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/welcome_eye_catching.jpg
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP/NotoSansJP-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansJP/NotoSansJP-Bold.ttf
          weight: 700

flutter_gen:
  fonts:
    enabled: true
    outputs:
      class_name: FontFamily

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: "launcher_icon"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  ios: true
  remove_alpha_ios: true
