name: flutter_birds
description: "A flutter project to tweet"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # l10n
  flutter_localizations:
    sdk: flutter
  intl: any

  # freezed
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

  # riverpod
  flutter_riverpod: ^2.5.1

  # firebase
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
